apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "wap.fullname" . }}
  labels:
    {{- include "wap.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "wap.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
  egress:
  - to:
    {{- range .Values.allowedCIDRs }}
    - ipBlock:
        cidr: - {{ . | quote }}
    {{- end }}
    ports:
    - protocol: TCP
      port: 80