apiVersion: v1
kind: Service
metadata:
  name: {{ include "wap.fullname" . }}
  labels:
    {{- include "wap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9200
      targetPort: wap
      protocol: UDP
      name: wap
    - port: 9201
      targetPort: wss
      protocol: UDP
      name: wss
  selector:
    {{- include "wap.selectorLabels" . | nindent 4 }}
