name: Docker Image Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get qemu-user-static
        run: sudo apt-get update && sudo apt-get install -y qemu-user-static
      - name: Configure Docker
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register
      - name: Build the Docker image
        run: |
          docker build -t maartje/wap:$GITHUB_SHA ./
      - name: Log in to registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "meyskens" --password-stdin
      - name: Push image
        run: docker push maartje/wap:$GITHUB_SHA
